[project]
name = "bumper"
version = "0.1.0"
description = "Add a short description here"
authors = ["Katherine Rosenfeld"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
start = "snakemake --cores 1"

[dependencies]
jupyter = ">=1.0.0,<1.1"
matplotlib = ">=3.8.4,<3.9"
seaborn = ">=0.13.2,<0.14"
openai = ">=1.30.1,<1.31"
scipy = ">=1.13.0,<1.14"
pycountry = ">=22.3.5,<22.4"
numpy = ">=1.26.4,<1.27"
termcolor = ">=2.4.0,<2.5"
snakemake = ">=8.11.3,<8.12"
pymc = ">=5.15.0,<5.16"
umap-learn = ">=0.5.5,<0.6"
distance = ">=0.1.3,<0.2"

[pypi-dependencies]
bumper = { path = "./bumper", editable = true}
measles = { path = "./measles", editable = true}
rugby = { path = "./rugby", editable = true}
